#pragma once

#include <BlazarECS/IGameEntity.h>
#include <BlazarECS/CTransform.h>
#include <BlazarECS/CAmbientLight.h>
#include <BlazarECS/CDirectionalLight.h>
#include <BlazarECS/CPointLight.h>
#include <BlazarECS/CSpotLight.h>
#include <BlazarECS/IComponent.h>
#include <BlazarECS/ISystem.h>
#include <BlazarECS/CMaterial.h>
#include <BlazarECS/CTessellation.h>
#include <BlazarECS/CMesh.h>
#include <BlazarECS/CInstances.h>
#include <BlazarECS/CCubeMap.h>
#include <BlazarECS/CCamera.h>
#include <BlazarECS/CCollisionObject.h>
#include <BlazarECS/CRigidBody.h>
#include <BlazarECS/ComponentTable.h>
#include <BlazarECS/CGameState.h>