SET(BULLET_LIBS
        Bullet3Dynamics
        BulletDynamics
        BulletSoftBody
        Bullet3Geometry
        Bullet3Collision
        BulletCollision
        BulletInverseDynamics
        LinearMath
        Bullet3Common
        )