ADD_DEFINITIONS(-DENGINE_NAMESPACE=BlazarEngine)
ADD_DEFINITIONS(-D_SCL_SECURE_NO_WARNINGS)
ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)
ADD_DEFINITIONS(-DDEBUG)
ADD_DEFINITIONS(-DG_VERBOSITY=3)
ADD_DEFINITIONS(-DGTEST_LANG_CXX11=1)
ADD_DEFINITIONS(-DROOT_DIR="${PROJECT_SOURCE_DIR}")

IF (WIN32)
    ADD_DEFINITIONS(-D_WIN32=1)
ENDIF()

SET(CMAKE_CXX_STANDARD 17)

IF(${BLAZAR_INSTALL_LIBS})
#${CMAKE_INSTALL_PREFIX}/
    SET(BLAZAR_INSTALL_LOCATION "" CACHE INTERNAL "BLAZAR_INSTALL_LOCATION")
ELSE()
    IF("${CMAKE_BUILD_TYPE}" STREQUAL "")
        SET(RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/build/BlazarEngine/)
    ELSE()
        SET(RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/build/BlazarEngine/${CMAKE_BUILD_TYPE}/)
    ENDIF()
    SET(BLAZAR_INSTALL_LOCATION ${RUNTIME_OUTPUT_DIRECTORY} CACHE INTERNAL "BLAZAR_INSTALL_LOCATION")
ENDIF()

IF(MSVC)
    ADD_COMPILE_OPTIONS(
        $<$<CONFIG:>:/MT>
        $<$<CONFIG:Debug>:/MTd> 
        $<$<CONFIG:Release>:/MT>
    )

    SET(CompilerFlags
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_RELEASE
        )

    FOREACH(CompilerFlag ${CompilerFlags})
        STRING(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
    ENDFOREACH()

ENDIF()
