SET(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE BOOL "" FORCE)
SET(ASSIMP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
SET(ASSIMP_INSTALL OFF CACHE BOOL "" FORCE)

SET(ASSIMP_NO_EXPORT ON CACHE BOOL "" FORCE)

ADD_SUBDIRECTORY("${CMAKE_SOURCE_DIR}/external/assimp")

INCLUDE_DIRECTORIES(
        "${CMAKE_SOURCE_DIR}/external/assimp/include"
        "${CMAKE_SOURCE_DIR}/external/assimp/code"
        "${ASSIMP_BINARY_DIR}/include"
)

LINK_DIRECTORIES(BlazarEngine
        ${ASSIMP_BINARY_DIR}
        ${ASSIMP_BINARY_DIR}/lib)