ADD_DEFINITIONS(-DENGINE_NAMESPACE=BlazarEngine)
ADD_DEFINITIONS(-D_SCL_SECURE_NO_WARNINGS)
ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)
ADD_DEFINITIONS(-DDEBUG)
ADD_DEFINITIONS(-DG_VERBOSITY=3)
ADD_DEFINITIONS(-DGTEST_LANG_CXX11=1)
ADD_DEFINITIONS(-DROOT_DIR="${PROJECT_SOURCE_DIR}")

MESSAGE("CMAKE SOURCE DIR: ${CMAKE_SOURCE_DIR}")
MESSAGE("PROJECT SOURCE DIR: ${PROJECT_SOURCE_DIR}")

SET(CMAKE_CXX_STANDARD 17)