SET(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
SET(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
SET(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)

INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/external/stb")
INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/external/miniz")
INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/external/vma")
INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/external/tinygltf")

ADD_SUBDIRECTORY("${PROJECT_SOURCE_DIR}/external/glm")
ADD_SUBDIRECTORY("${PROJECT_SOURCE_DIR}/external/glfw")

LINK_LIBRARIES(glm)
LINK_LIBRARIES(glfw)
