#OPTION(INSTALL_LIBS ON)
#OPTION(BUILD_UNIT_TESTS OFF)
#OPTION(BUILD_OPENGL3_DEMOS OFF)
#OPTION(BUILD_BULLET2_DEMOS OFF)
#SET(PKGCONFIG_INSTALL_PREFIX ${PROJECT_BINARY_DIR}/external/bullet3/libs)

SET(OSDIR "unix")
IF (WIN32)
    SET(OSDIR "win")
ENDIF()

INCLUDE_DIRECTORIES("${PROJECT_SOURCE_DIR}/build/bullet3/${OSDIR}/include/bullet")
LINK_DIRECTORIES("${PROJECT_SOURCE_DIR}/build/bullet3/${OSDIR}/lib")

LIST(APPEND BlazarSources "${PROJECT_SOURCE_DIR}/external/bullet3/include")